version: 2

sources:
  - name: edge
    database: "{{ env_var('MSSQL_DB', 'edge') }}"
    schema: dbo
    tables:
      - name: enrollment
        description: "Enrollment spans (input) used by the DIY model."
        columns:
          - name: MemberID
            description: "Unique member identifier used to join inputs."
          - name: EffDat
            description: "Coverage effective date for the span."
          - name: ExpDat
            description: "Coverage end date for the span."
          - name: HIOS_ID
            description: "Plan HIOS identifier (including CSR variant)."
          - name: BirthDate
            description: "Member birth date used for age calculations."
          - name: Gender
            description: "Member gender used for coefficient selection."
      - name: medicalclaims
        description: "Medical claim lines (input) used by the DIY model."
        columns:
          - name: MemberID
            description: "Member identifier; joins to Enrollment."
          - name: ClaimNumber
            description: "Claim identifier; joins to Supplemental."
          - name: ServiceCode
            description: "Procedure/service code used for eligibility and RXC mapping."
          - name: LineServiceDateFrom
            description: "Service date used for effective-dated joins and eligibility."
          - name: PaidDate
            description: "Paid date (not always used for eligibility logic)."
      - name: pharmacyclaims
        description: "Pharmacy claim lines (input) used by the DIY model."
        columns:
          - name: MemberID
            description: "Member identifier; joins to Enrollment."
          - name: ClaimNumber
            description: "Claim identifier."
          - name: NDC
            description: "National Drug Code used to map to RXC."
          - name: FilledDate
            description: "Fill date used for eligibility and mapping."
          - name: PaidDate
            description: "Paid date (not always used for eligibility logic)."
      - name: supplemental
        description: "Supplemental diagnoses (input), joined to MedicalClaims by ClaimNumber."
        columns:
          - name: ClaimNumber
            description: "Claim identifier; joins to MedicalClaims."
          - name: DX
            description: "Diagnosis code associated to the claim."
          - name: AddDeleteFlag
            description: "Indicates add/delete of diagnosis records."
      - name: hcc_list
        description: "DIY model output table populated by DIY-Model-Script/DIY Model Script.sql."
        columns:
          - name: MBR_ID
            description: "Member identifier (derived from Enrollment.MemberID)."
          - name: eff_date
            description: "Coverage effective date for the record."
          - name: exp_date
            description: "Coverage end date for the record."
          - name: risk_score
            description: "Calculated risk score for the member/span."
          - name: metal
            description: "Metal level on the coverage record (e.g., Bronze/Silver/Gold/Platinum/Catastrophic)."
          - name: hios
            description: "HIOS identifier for the plan (including CSR variant when present)."
