version: 2

sources:
  - name: edge
    database: "{{ env_var('MSSQL_DB', 'edge') }}"
    schema: dbo
    tables:
      - name: Enrollment
        description: "Enrollment spans (input) used by the DIY model."
        columns:
          - name: MemberID
            description: "Unique member identifier used to join inputs."
          - name: EffDat
            description: "Coverage effective date for the span."
          - name: ExpDat
            description: "Coverage end date for the span."
          - name: HIOS_ID
            description: "Plan HIOS identifier (including CSR variant)."
          - name: BirthDate
            description: "Member birth date used for age calculations."
          - name: Gender
            description: "Member gender used for coefficient selection."
      - name: MedicalClaims
        description: "Medical claim lines (input) used by the DIY model."
        columns:
          - name: MemberID
            description: "Member identifier; joins to Enrollment."
          - name: ClaimNumber
            description: "Claim identifier; joins to Supplemental."
          - name: ServiceCode
            description: "Procedure/service code used for eligibility and RXC mapping."
          - name: LineServiceDateFrom
            description: "Service date used for effective-dated joins and eligibility."
          - name: PaidDate
            description: "Paid date (not always used for eligibility logic)."
      - name: PharmacyClaims
        description: "Pharmacy claim lines (input) used by the DIY model."
        columns:
          - name: MemberID
            description: "Member identifier; joins to Enrollment."
          - name: ClaimNumber
            description: "Claim identifier."
          - name: NDC
            description: "National Drug Code used to map to RXC."
          - name: FilledDate
            description: "Fill date used for eligibility and mapping."
          - name: PaidDate
            description: "Paid date (not always used for eligibility logic)."
      - name: Supplemental
        description: "Supplemental diagnoses (input), joined to MedicalClaims by ClaimNumber."
        columns:
          - name: ClaimNumber
            description: "Claim identifier; joins to MedicalClaims."
          - name: DX
            description: "Diagnosis code associated to the claim."
          - name: AddDeleteFlag
            description: "Indicates add/delete of diagnosis records."
      - name: hcc_list
        description: "DIY model output table populated by DIY-Model-Script/DIY Model Script.sql."
        columns:
          - name: MBR_ID
            description: "Member identifier (derived from Enrollment.MemberID)."
          - name: eff_date
            description: "Coverage effective date for the record."
          - name: exp_date
            description: "Coverage end date for the record."
          - name: risk_score
            description: "Calculated risk score for the member/span."
          - name: metal
            description: "Metal level on the coverage record (e.g., Bronze/Silver/Gold/Platinum/Catastrophic)."
          - name: hios
            description: "HIOS identifier for the plan (including CSR variant when present)."

      - name: DX_Mapping_Table
        description: "Maps diagnosis codes to HHS-HCC condition categories (CC) and additional CCs, with age/sex and effective-date constraints."
        columns:
          - name: DGNS_CD
            description: "Diagnosis code (ICD)."
          - name: DGNS_CD_EFF_STRT_DT
            description: "Diagnosis code mapping effective start date."
          - name: DGNS_CD_EFF_END_DT
            description: "Diagnosis code mapping effective end date."
          - name: MIN_AGE_DGNS_INCLUDE
            description: "Minimum age (inclusive) for diagnosis-to-CC mapping applicability."
          - name: MAX_AGE_DGNS_EXCLUDE
            description: "Maximum age (exclusive) for diagnosis-to-CC mapping applicability."
          - name: CC_AGE_SPLIT_MIN_AGE_INC
            description: "Minimum age (inclusive) for CC split applicability."
          - name: CC_AGE_SPLIT_MAX_AGE_EXC
            description: "Maximum age (exclusive) for CC split applicability."
          - name: CC_SEX_SPLIT
            description: "Sex restriction for CC split (e.g., M/F/ALL)."
          - name: CC_CD
            description: "Primary condition category code."
          - name: ACC_CD
            description: "Additional condition category code (if applicable)."

      - name: NDC_RXC
        description: "Maps NDC drug codes to RxC categories used in the model."
        columns:
          - name: NDC
            description: "National Drug Code (NDC)."
          - name: RXC
            description: "RxC category code."

      - name: HCPCSRXC
        description: "Maps HCPCS codes to RXC categories (crosswalk used for certain service codes)."
        columns:
          - name: HCPCS_CODE
            description: "HCPCS procedure code."
          - name: RXC
            description: "RxC category code."

      - name: ServiceCodeReference
        description: "Service code reference table with service type, effective dates, and risk adjustment eligibility indicator."
        columns:
          - name: SRVC_CD
            description: "Service code."
          - name: SRVC_TYPE_CD
            description: "Service type code."
          - name: SRVC_CD_EFCTV_STRT_DT
            description: "Service code effective start date."
          - name: SRVC_CD_EFCTV_END_DT
            description: "Service code effective end date."
          - name: CPT_HCPCSELGBL_RISKADJSTMT_IND
            description: "Risk adjustment eligible indicator (Y/N)."

      - name: RiskScoreFactors
        description: "Model coefficients by model year and metal level used to compute risk scores."
        columns:
          - name: Model
            description: "Model identifier (e.g., adult/child/infant)."
          - name: Variable
            description: "Variable name (factor) used in the risk score formula."
          - name: Variable_Used_in_Risk_Score_Formula
            description: "Variable inclusion flag/name used in the formula."
          - name: Platinum_Level
            description: "Coefficient at Platinum AV/metal level."
          - name: Gold_Level
            description: "Coefficient at Gold AV/metal level."
          - name: Silver_Level
            description: "Coefficient at Silver AV/metal level."
          - name: Bronze_Level
            description: "Coefficient at Bronze AV/metal level."
          - name: Catastrophic_Level
            description: "Coefficient at Catastrophic AV/metal level."
          - name: Model_Year
            description: "Model year for the coefficients."

      - name: CSR_Adj_Factors
        description: "CSR adjustment factors by CSR code and model year."
        columns:
          - name: CSR_Code
            description: "CSR code."
          - name: CSR_Desc
            description: "CSR category description."
          - name: model_year
            description: "Model year the CSR factor applies to."
          - name: adj_factor
            description: "CSR adjustment factor multiplier."

      - name: Federal_Age_Curve
        description: "Federal age curve premium ratios by age."
        columns:
          - name: Age
            description: "Age in years."
          - name: Premium_Ratio
            description: "Premium ratio (age factor) for the given age."

      - name: metal_level_mapping
        description: "Maps metal level to induced demand factor (IDF) and actuarial value (AV)."
        columns:
          - name: metal
            description: "Metal level name (e.g., Bronze, Silver, Gold)."
          - name: idf
            description: "Induced demand factor."
          - name: av
            description: "Actuarial value."

      - name: Rating_Area_CountyMap
        description: "Maps state and geography (county/zip) to rating area and related geographic metadata."
        columns:
          - name: State
            description: "State name."
          - name: Rating_Area
            description: "Rating area label."
          - name: County
            description: "County name (if applicable)."
          - name: COUNTY2
            description: "County name (uppercased/normalized)."
          - name: Zip
            description: "Zip prefix or zip code (if applicable)."
          - name: Market_Geographic_Rating_Divisions
            description: "Geographic division type used for rating (e.g., counties, MSAs)."
          - name: FFM
            description: "Federally-facilitated marketplace indicator."
          - name: State_Abb
            description: "State abbreviation."
          - name: FIPS
            description: "FIPS code (if applicable)."

      - name: Statewide_RA_Factors
        description: "Statewide rating area factor inputs by market and year."
        columns:
          - name: State
            description: "State abbreviation."
          - name: RA_Adj_Avg_Pre
            description: "Risk adjustment adjusted average premium."
          - name: Avg_pre
            description: "Average premium."
          - name: PLRS
            description: "Plan liability risk score (PLRS)."
          - name: ARF
            description: "Allowable rating factor (ARF)."
          - name: AV
            description: "Actuarial value."
          - name: IDF
            description: "Induced demand factor."
          - name: MM
            description: "Member months."
          - name: Market
            description: "Market indicator."
          - name: Year
            description: "Calendar/model year."

      - name: GCF
        description: "Geographic cost factors by state, rating area, market, and year."
        columns:
          - name: State
            description: "State abbreviation."
          - name: Rating_Area
            description: "Numeric rating area."
          - name: GCF
            description: "Geographic cost factor."
          - name: Billable_Member_Months
            description: "Billable member months used in the factor derivation."
          - name: Year
            description: "Calendar/model year."
          - name: Market
            description: "Market indicator."
          - name: rating_area_text
            description: "Computed rating area label (e.g., R-<STATE><NNN>)."
