version: 2

models:
  - name: agg_member_risk_score
    description: "One row per member with max risk scores from `dbo.hcc_list`."
  - name: fct_hcc_list
    description: "Fact-style view of HCC results (currently passthrough)."
